/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVerificationBotRouteImport } from './routes/dashboard.verification-bot'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPurchaseRouteImport } from './routes/dashboard.purchase'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardDiscordSpamRouteImport } from './routes/dashboard.discord-spam'
import { Route as DashboardDiscordBotRouteImport } from './routes/dashboard.discord-bot'
import { Route as DashboardDiscordAutoReplyRouteImport } from './routes/dashboard.discord-auto-reply'
import { Route as DashboardBotsRouteImport } from './routes/dashboard.bots'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiDiscordLogoutRouteImport } from './routes/api/discord.logout'
import { Route as ApiDiscordLoginRouteImport } from './routes/api/discord.login'
import { Route as ApiDiscordInteractionsRouteImport } from './routes/api/discord/interactions'
import { Route as ApiDiscordCallbackRouteImport } from './routes/api/discord.callback'
import { Route as ApiBotsStreamRouteImport } from './routes/api/bots/stream'
import { Route as ApiBotsLogsRouteImport } from './routes/api/bots/logs'
import { Route as ApiBotsAllStatusRouteImport } from './routes/api/bots/all-status'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiPublicNowpaymentsWebhookRouteImport } from './routes/api/public/nowpayments/webhook'
import { Route as ApiBotsWorkerUpdateRouteImport } from './routes/api/bots/worker/update'
import { Route as ApiBotsWorkerPollRouteImport } from './routes/api/bots/worker/poll'
import { Route as ApiBotsWorkerLogRouteImport } from './routes/api/bots/worker/log'
import { Route as ApiBotsMcStopRouteImport } from './routes/api/bots/mc/stop'
import { Route as ApiBotsMcStatusRouteImport } from './routes/api/bots/mc/status'
import { Route as ApiBotsMcStartRouteImport } from './routes/api/bots/mc/start'
import { Route as ApiBotsMcPingRouteImport } from './routes/api/bots/mc/ping'
import { Route as ApiBotsDiscordStopRouteImport } from './routes/api/bots/discord/stop'
import { Route as ApiBotsDiscordStatusRouteImport } from './routes/api/bots/discord/status'
import { Route as ApiBotsDiscordStartRouteImport } from './routes/api/bots/discord/start'
import { Route as ApiBotsDiscordAutoreplyStopRouteImport } from './routes/api/bots/discord-autoreply/stop'
import { Route as ApiBotsDiscordAutoreplyStatusRouteImport } from './routes/api/bots/discord-autoreply/status'
import { Route as ApiBotsDiscordAutoreplyStartRouteImport } from './routes/api/bots/discord-autoreply/start'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVerificationBotRoute =
  DashboardVerificationBotRouteImport.update({
    id: '/verification-bot',
    path: '/verification-bot',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPurchaseRoute = DashboardPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiscordSpamRoute = DashboardDiscordSpamRouteImport.update({
  id: '/discord-spam',
  path: '/discord-spam',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiscordBotRoute = DashboardDiscordBotRouteImport.update({
  id: '/discord-bot',
  path: '/discord-bot',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiscordAutoReplyRoute =
  DashboardDiscordAutoReplyRouteImport.update({
    id: '/discord-auto-reply',
    path: '/discord-auto-reply',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBotsRoute = DashboardBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordLogoutRoute = ApiDiscordLogoutRouteImport.update({
  id: '/api/discord/logout',
  path: '/api/discord/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordLoginRoute = ApiDiscordLoginRouteImport.update({
  id: '/api/discord/login',
  path: '/api/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordInteractionsRoute = ApiDiscordInteractionsRouteImport.update({
  id: '/api/discord/interactions',
  path: '/api/discord/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordCallbackRoute = ApiDiscordCallbackRouteImport.update({
  id: '/api/discord/callback',
  path: '/api/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsStreamRoute = ApiBotsStreamRouteImport.update({
  id: '/api/bots/stream',
  path: '/api/bots/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsLogsRoute = ApiBotsLogsRouteImport.update({
  id: '/api/bots/logs',
  path: '/api/bots/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsAllStatusRoute = ApiBotsAllStatusRouteImport.update({
  id: '/api/bots/all-status',
  path: '/api/bots/all-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNowpaymentsWebhookRoute =
  ApiPublicNowpaymentsWebhookRouteImport.update({
    id: '/api/public/nowpayments/webhook',
    path: '/api/public/nowpayments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBotsWorkerUpdateRoute = ApiBotsWorkerUpdateRouteImport.update({
  id: '/api/bots/worker/update',
  path: '/api/bots/worker/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsWorkerPollRoute = ApiBotsWorkerPollRouteImport.update({
  id: '/api/bots/worker/poll',
  path: '/api/bots/worker/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsWorkerLogRoute = ApiBotsWorkerLogRouteImport.update({
  id: '/api/bots/worker/log',
  path: '/api/bots/worker/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsMcStopRoute = ApiBotsMcStopRouteImport.update({
  id: '/api/bots/mc/stop',
  path: '/api/bots/mc/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsMcStatusRoute = ApiBotsMcStatusRouteImport.update({
  id: '/api/bots/mc/status',
  path: '/api/bots/mc/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsMcStartRoute = ApiBotsMcStartRouteImport.update({
  id: '/api/bots/mc/start',
  path: '/api/bots/mc/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsMcPingRoute = ApiBotsMcPingRouteImport.update({
  id: '/api/bots/mc/ping',
  path: '/api/bots/mc/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsDiscordStopRoute = ApiBotsDiscordStopRouteImport.update({
  id: '/api/bots/discord/stop',
  path: '/api/bots/discord/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsDiscordStatusRoute = ApiBotsDiscordStatusRouteImport.update({
  id: '/api/bots/discord/status',
  path: '/api/bots/discord/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsDiscordStartRoute = ApiBotsDiscordStartRouteImport.update({
  id: '/api/bots/discord/start',
  path: '/api/bots/discord/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsDiscordAutoreplyStopRoute =
  ApiBotsDiscordAutoreplyStopRouteImport.update({
    id: '/api/bots/discord-autoreply/stop',
    path: '/api/bots/discord-autoreply/stop',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBotsDiscordAutoreplyStatusRoute =
  ApiBotsDiscordAutoreplyStatusRouteImport.update({
    id: '/api/bots/discord-autoreply/status',
    path: '/api/bots/discord-autoreply/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBotsDiscordAutoreplyStartRoute =
  ApiBotsDiscordAutoreplyStartRouteImport.update({
    id: '/api/bots/discord-autoreply/start',
    path: '/api/bots/discord-autoreply/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/me': typeof ApiMeRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bots': typeof DashboardBotsRoute
  '/dashboard/discord-auto-reply': typeof DashboardDiscordAutoReplyRoute
  '/dashboard/discord-bot': typeof DashboardDiscordBotRoute
  '/dashboard/discord-spam': typeof DashboardDiscordSpamRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/purchase': typeof DashboardPurchaseRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/verification-bot': typeof DashboardVerificationBotRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/bots/all-status': typeof ApiBotsAllStatusRoute
  '/api/bots/logs': typeof ApiBotsLogsRoute
  '/api/bots/stream': typeof ApiBotsStreamRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
  '/api/discord/interactions': typeof ApiDiscordInteractionsRoute
  '/api/discord/login': typeof ApiDiscordLoginRoute
  '/api/discord/logout': typeof ApiDiscordLogoutRoute
  '/api/bots/discord-autoreply/start': typeof ApiBotsDiscordAutoreplyStartRoute
  '/api/bots/discord-autoreply/status': typeof ApiBotsDiscordAutoreplyStatusRoute
  '/api/bots/discord-autoreply/stop': typeof ApiBotsDiscordAutoreplyStopRoute
  '/api/bots/discord/start': typeof ApiBotsDiscordStartRoute
  '/api/bots/discord/status': typeof ApiBotsDiscordStatusRoute
  '/api/bots/discord/stop': typeof ApiBotsDiscordStopRoute
  '/api/bots/mc/ping': typeof ApiBotsMcPingRoute
  '/api/bots/mc/start': typeof ApiBotsMcStartRoute
  '/api/bots/mc/status': typeof ApiBotsMcStatusRoute
  '/api/bots/mc/stop': typeof ApiBotsMcStopRoute
  '/api/bots/worker/log': typeof ApiBotsWorkerLogRoute
  '/api/bots/worker/poll': typeof ApiBotsWorkerPollRoute
  '/api/bots/worker/update': typeof ApiBotsWorkerUpdateRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/me': typeof ApiMeRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bots': typeof DashboardBotsRoute
  '/dashboard/discord-auto-reply': typeof DashboardDiscordAutoReplyRoute
  '/dashboard/discord-bot': typeof DashboardDiscordBotRoute
  '/dashboard/discord-spam': typeof DashboardDiscordSpamRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/purchase': typeof DashboardPurchaseRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/verification-bot': typeof DashboardVerificationBotRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/bots/all-status': typeof ApiBotsAllStatusRoute
  '/api/bots/logs': typeof ApiBotsLogsRoute
  '/api/bots/stream': typeof ApiBotsStreamRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
  '/api/discord/interactions': typeof ApiDiscordInteractionsRoute
  '/api/discord/login': typeof ApiDiscordLoginRoute
  '/api/discord/logout': typeof ApiDiscordLogoutRoute
  '/api/bots/discord-autoreply/start': typeof ApiBotsDiscordAutoreplyStartRoute
  '/api/bots/discord-autoreply/status': typeof ApiBotsDiscordAutoreplyStatusRoute
  '/api/bots/discord-autoreply/stop': typeof ApiBotsDiscordAutoreplyStopRoute
  '/api/bots/discord/start': typeof ApiBotsDiscordStartRoute
  '/api/bots/discord/status': typeof ApiBotsDiscordStatusRoute
  '/api/bots/discord/stop': typeof ApiBotsDiscordStopRoute
  '/api/bots/mc/ping': typeof ApiBotsMcPingRoute
  '/api/bots/mc/start': typeof ApiBotsMcStartRoute
  '/api/bots/mc/status': typeof ApiBotsMcStatusRoute
  '/api/bots/mc/stop': typeof ApiBotsMcStopRoute
  '/api/bots/worker/log': typeof ApiBotsWorkerLogRoute
  '/api/bots/worker/poll': typeof ApiBotsWorkerPollRoute
  '/api/bots/worker/update': typeof ApiBotsWorkerUpdateRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/me': typeof ApiMeRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bots': typeof DashboardBotsRoute
  '/dashboard/discord-auto-reply': typeof DashboardDiscordAutoReplyRoute
  '/dashboard/discord-bot': typeof DashboardDiscordBotRoute
  '/dashboard/discord-spam': typeof DashboardDiscordSpamRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/purchase': typeof DashboardPurchaseRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/verification-bot': typeof DashboardVerificationBotRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/bots/all-status': typeof ApiBotsAllStatusRoute
  '/api/bots/logs': typeof ApiBotsLogsRoute
  '/api/bots/stream': typeof ApiBotsStreamRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
  '/api/discord/interactions': typeof ApiDiscordInteractionsRoute
  '/api/discord/login': typeof ApiDiscordLoginRoute
  '/api/discord/logout': typeof ApiDiscordLogoutRoute
  '/api/bots/discord-autoreply/start': typeof ApiBotsDiscordAutoreplyStartRoute
  '/api/bots/discord-autoreply/status': typeof ApiBotsDiscordAutoreplyStatusRoute
  '/api/bots/discord-autoreply/stop': typeof ApiBotsDiscordAutoreplyStopRoute
  '/api/bots/discord/start': typeof ApiBotsDiscordStartRoute
  '/api/bots/discord/status': typeof ApiBotsDiscordStatusRoute
  '/api/bots/discord/stop': typeof ApiBotsDiscordStopRoute
  '/api/bots/mc/ping': typeof ApiBotsMcPingRoute
  '/api/bots/mc/start': typeof ApiBotsMcStartRoute
  '/api/bots/mc/status': typeof ApiBotsMcStatusRoute
  '/api/bots/mc/stop': typeof ApiBotsMcStopRoute
  '/api/bots/worker/log': typeof ApiBotsWorkerLogRoute
  '/api/bots/worker/poll': typeof ApiBotsWorkerPollRoute
  '/api/bots/worker/update': typeof ApiBotsWorkerUpdateRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/api/me'
    | '/dashboard/billing'
    | '/dashboard/bots'
    | '/dashboard/discord-auto-reply'
    | '/dashboard/discord-bot'
    | '/dashboard/discord-spam'
    | '/dashboard/logs'
    | '/dashboard/purchase'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/verification-bot'
    | '/dashboard/'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/bots/all-status'
    | '/api/bots/logs'
    | '/api/bots/stream'
    | '/api/discord/callback'
    | '/api/discord/interactions'
    | '/api/discord/login'
    | '/api/discord/logout'
    | '/api/bots/discord-autoreply/start'
    | '/api/bots/discord-autoreply/status'
    | '/api/bots/discord-autoreply/stop'
    | '/api/bots/discord/start'
    | '/api/bots/discord/status'
    | '/api/bots/discord/stop'
    | '/api/bots/mc/ping'
    | '/api/bots/mc/start'
    | '/api/bots/mc/status'
    | '/api/bots/mc/stop'
    | '/api/bots/worker/log'
    | '/api/bots/worker/poll'
    | '/api/bots/worker/update'
    | '/api/public/nowpayments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/me'
    | '/dashboard/billing'
    | '/dashboard/bots'
    | '/dashboard/discord-auto-reply'
    | '/dashboard/discord-bot'
    | '/dashboard/discord-spam'
    | '/dashboard/logs'
    | '/dashboard/purchase'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/verification-bot'
    | '/dashboard'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/bots/all-status'
    | '/api/bots/logs'
    | '/api/bots/stream'
    | '/api/discord/callback'
    | '/api/discord/interactions'
    | '/api/discord/login'
    | '/api/discord/logout'
    | '/api/bots/discord-autoreply/start'
    | '/api/bots/discord-autoreply/status'
    | '/api/bots/discord-autoreply/stop'
    | '/api/bots/discord/start'
    | '/api/bots/discord/status'
    | '/api/bots/discord/stop'
    | '/api/bots/mc/ping'
    | '/api/bots/mc/start'
    | '/api/bots/mc/status'
    | '/api/bots/mc/stop'
    | '/api/bots/worker/log'
    | '/api/bots/worker/poll'
    | '/api/bots/worker/update'
    | '/api/public/nowpayments/webhook'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/api/me'
    | '/dashboard/billing'
    | '/dashboard/bots'
    | '/dashboard/discord-auto-reply'
    | '/dashboard/discord-bot'
    | '/dashboard/discord-spam'
    | '/dashboard/logs'
    | '/dashboard/purchase'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/verification-bot'
    | '/dashboard/'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/bots/all-status'
    | '/api/bots/logs'
    | '/api/bots/stream'
    | '/api/discord/callback'
    | '/api/discord/interactions'
    | '/api/discord/login'
    | '/api/discord/logout'
    | '/api/bots/discord-autoreply/start'
    | '/api/bots/discord-autoreply/status'
    | '/api/bots/discord-autoreply/stop'
    | '/api/bots/discord/start'
    | '/api/bots/discord/status'
    | '/api/bots/discord/stop'
    | '/api/bots/mc/ping'
    | '/api/bots/mc/start'
    | '/api/bots/mc/status'
    | '/api/bots/mc/stop'
    | '/api/bots/worker/log'
    | '/api/bots/worker/poll'
    | '/api/bots/worker/update'
    | '/api/public/nowpayments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiBotsAllStatusRoute: typeof ApiBotsAllStatusRoute
  ApiBotsLogsRoute: typeof ApiBotsLogsRoute
  ApiBotsStreamRoute: typeof ApiBotsStreamRoute
  ApiDiscordCallbackRoute: typeof ApiDiscordCallbackRoute
  ApiDiscordInteractionsRoute: typeof ApiDiscordInteractionsRoute
  ApiDiscordLoginRoute: typeof ApiDiscordLoginRoute
  ApiDiscordLogoutRoute: typeof ApiDiscordLogoutRoute
  ApiBotsDiscordAutoreplyStartRoute: typeof ApiBotsDiscordAutoreplyStartRoute
  ApiBotsDiscordAutoreplyStatusRoute: typeof ApiBotsDiscordAutoreplyStatusRoute
  ApiBotsDiscordAutoreplyStopRoute: typeof ApiBotsDiscordAutoreplyStopRoute
  ApiBotsDiscordStartRoute: typeof ApiBotsDiscordStartRoute
  ApiBotsDiscordStatusRoute: typeof ApiBotsDiscordStatusRoute
  ApiBotsDiscordStopRoute: typeof ApiBotsDiscordStopRoute
  ApiBotsMcPingRoute: typeof ApiBotsMcPingRoute
  ApiBotsMcStartRoute: typeof ApiBotsMcStartRoute
  ApiBotsMcStatusRoute: typeof ApiBotsMcStatusRoute
  ApiBotsMcStopRoute: typeof ApiBotsMcStopRoute
  ApiBotsWorkerLogRoute: typeof ApiBotsWorkerLogRoute
  ApiBotsWorkerPollRoute: typeof ApiBotsWorkerPollRoute
  ApiBotsWorkerUpdateRoute: typeof ApiBotsWorkerUpdateRoute
  ApiPublicNowpaymentsWebhookRoute: typeof ApiPublicNowpaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/verification-bot': {
      id: '/dashboard/verification-bot'
      path: '/verification-bot'
      fullPath: '/dashboard/verification-bot'
      preLoaderRoute: typeof DashboardVerificationBotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/purchase': {
      id: '/dashboard/purchase'
      path: '/purchase'
      fullPath: '/dashboard/purchase'
      preLoaderRoute: typeof DashboardPurchaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/discord-spam': {
      id: '/dashboard/discord-spam'
      path: '/discord-spam'
      fullPath: '/dashboard/discord-spam'
      preLoaderRoute: typeof DashboardDiscordSpamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/discord-bot': {
      id: '/dashboard/discord-bot'
      path: '/discord-bot'
      fullPath: '/dashboard/discord-bot'
      preLoaderRoute: typeof DashboardDiscordBotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/discord-auto-reply': {
      id: '/dashboard/discord-auto-reply'
      path: '/discord-auto-reply'
      fullPath: '/dashboard/discord-auto-reply'
      preLoaderRoute: typeof DashboardDiscordAutoReplyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bots': {
      id: '/dashboard/bots'
      path: '/bots'
      fullPath: '/dashboard/bots'
      preLoaderRoute: typeof DashboardBotsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/logout': {
      id: '/api/discord/logout'
      path: '/api/discord/logout'
      fullPath: '/api/discord/logout'
      preLoaderRoute: typeof ApiDiscordLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/login': {
      id: '/api/discord/login'
      path: '/api/discord/login'
      fullPath: '/api/discord/login'
      preLoaderRoute: typeof ApiDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/interactions': {
      id: '/api/discord/interactions'
      path: '/api/discord/interactions'
      fullPath: '/api/discord/interactions'
      preLoaderRoute: typeof ApiDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/callback': {
      id: '/api/discord/callback'
      path: '/api/discord/callback'
      fullPath: '/api/discord/callback'
      preLoaderRoute: typeof ApiDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/stream': {
      id: '/api/bots/stream'
      path: '/api/bots/stream'
      fullPath: '/api/bots/stream'
      preLoaderRoute: typeof ApiBotsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/logs': {
      id: '/api/bots/logs'
      path: '/api/bots/logs'
      fullPath: '/api/bots/logs'
      preLoaderRoute: typeof ApiBotsLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/all-status': {
      id: '/api/bots/all-status'
      path: '/api/bots/all-status'
      fullPath: '/api/bots/all-status'
      preLoaderRoute: typeof ApiBotsAllStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nowpayments/webhook': {
      id: '/api/public/nowpayments/webhook'
      path: '/api/public/nowpayments/webhook'
      fullPath: '/api/public/nowpayments/webhook'
      preLoaderRoute: typeof ApiPublicNowpaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/worker/update': {
      id: '/api/bots/worker/update'
      path: '/api/bots/worker/update'
      fullPath: '/api/bots/worker/update'
      preLoaderRoute: typeof ApiBotsWorkerUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/worker/poll': {
      id: '/api/bots/worker/poll'
      path: '/api/bots/worker/poll'
      fullPath: '/api/bots/worker/poll'
      preLoaderRoute: typeof ApiBotsWorkerPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/worker/log': {
      id: '/api/bots/worker/log'
      path: '/api/bots/worker/log'
      fullPath: '/api/bots/worker/log'
      preLoaderRoute: typeof ApiBotsWorkerLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/mc/stop': {
      id: '/api/bots/mc/stop'
      path: '/api/bots/mc/stop'
      fullPath: '/api/bots/mc/stop'
      preLoaderRoute: typeof ApiBotsMcStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/mc/status': {
      id: '/api/bots/mc/status'
      path: '/api/bots/mc/status'
      fullPath: '/api/bots/mc/status'
      preLoaderRoute: typeof ApiBotsMcStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/mc/start': {
      id: '/api/bots/mc/start'
      path: '/api/bots/mc/start'
      fullPath: '/api/bots/mc/start'
      preLoaderRoute: typeof ApiBotsMcStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/mc/ping': {
      id: '/api/bots/mc/ping'
      path: '/api/bots/mc/ping'
      fullPath: '/api/bots/mc/ping'
      preLoaderRoute: typeof ApiBotsMcPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/discord/stop': {
      id: '/api/bots/discord/stop'
      path: '/api/bots/discord/stop'
      fullPath: '/api/bots/discord/stop'
      preLoaderRoute: typeof ApiBotsDiscordStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/discord/status': {
      id: '/api/bots/discord/status'
      path: '/api/bots/discord/status'
      fullPath: '/api/bots/discord/status'
      preLoaderRoute: typeof ApiBotsDiscordStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/discord/start': {
      id: '/api/bots/discord/start'
      path: '/api/bots/discord/start'
      fullPath: '/api/bots/discord/start'
      preLoaderRoute: typeof ApiBotsDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/discord-autoreply/stop': {
      id: '/api/bots/discord-autoreply/stop'
      path: '/api/bots/discord-autoreply/stop'
      fullPath: '/api/bots/discord-autoreply/stop'
      preLoaderRoute: typeof ApiBotsDiscordAutoreplyStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/discord-autoreply/status': {
      id: '/api/bots/discord-autoreply/status'
      path: '/api/bots/discord-autoreply/status'
      fullPath: '/api/bots/discord-autoreply/status'
      preLoaderRoute: typeof ApiBotsDiscordAutoreplyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/discord-autoreply/start': {
      id: '/api/bots/discord-autoreply/start'
      path: '/api/bots/discord-autoreply/start'
      fullPath: '/api/bots/discord-autoreply/start'
      preLoaderRoute: typeof ApiBotsDiscordAutoreplyStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBotsRoute: typeof DashboardBotsRoute
  DashboardDiscordAutoReplyRoute: typeof DashboardDiscordAutoReplyRoute
  DashboardDiscordBotRoute: typeof DashboardDiscordBotRoute
  DashboardDiscordSpamRoute: typeof DashboardDiscordSpamRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardPurchaseRoute: typeof DashboardPurchaseRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardVerificationBotRoute: typeof DashboardVerificationBotRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBotsRoute: DashboardBotsRoute,
  DashboardDiscordAutoReplyRoute: DashboardDiscordAutoReplyRoute,
  DashboardDiscordBotRoute: DashboardDiscordBotRoute,
  DashboardDiscordSpamRoute: DashboardDiscordSpamRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardPurchaseRoute: DashboardPurchaseRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardVerificationBotRoute: DashboardVerificationBotRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiMeRoute: ApiMeRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiBotsAllStatusRoute: ApiBotsAllStatusRoute,
  ApiBotsLogsRoute: ApiBotsLogsRoute,
  ApiBotsStreamRoute: ApiBotsStreamRoute,
  ApiDiscordCallbackRoute: ApiDiscordCallbackRoute,
  ApiDiscordInteractionsRoute: ApiDiscordInteractionsRoute,
  ApiDiscordLoginRoute: ApiDiscordLoginRoute,
  ApiDiscordLogoutRoute: ApiDiscordLogoutRoute,
  ApiBotsDiscordAutoreplyStartRoute: ApiBotsDiscordAutoreplyStartRoute,
  ApiBotsDiscordAutoreplyStatusRoute: ApiBotsDiscordAutoreplyStatusRoute,
  ApiBotsDiscordAutoreplyStopRoute: ApiBotsDiscordAutoreplyStopRoute,
  ApiBotsDiscordStartRoute: ApiBotsDiscordStartRoute,
  ApiBotsDiscordStatusRoute: ApiBotsDiscordStatusRoute,
  ApiBotsDiscordStopRoute: ApiBotsDiscordStopRoute,
  ApiBotsMcPingRoute: ApiBotsMcPingRoute,
  ApiBotsMcStartRoute: ApiBotsMcStartRoute,
  ApiBotsMcStatusRoute: ApiBotsMcStatusRoute,
  ApiBotsMcStopRoute: ApiBotsMcStopRoute,
  ApiBotsWorkerLogRoute: ApiBotsWorkerLogRoute,
  ApiBotsWorkerPollRoute: ApiBotsWorkerPollRoute,
  ApiBotsWorkerUpdateRoute: ApiBotsWorkerUpdateRoute,
  ApiPublicNowpaymentsWebhookRoute: ApiPublicNowpaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
